### ISSUE TITLE
cluster (only one end overlapping) breakpoints using InteractionSet

### ISSUE THREAD

**Issue by crazyhottommy** [LTLA/archive-InteractionSet#14]
Hi there,
Thanks for this package. I have been using it to cluster my  breakpoints as I took down notes here http://crazyhottommy.blogspot.com/2016/03/breakpoints-clustering-for-structural.html
In the post, I used your method to cluster breakpoints which have both ends overlapping.

Now I have another question:

```
----|------|-------|------|----------------------------------------------------  A-B
---------------------|--------|----------|-------|-----------------------------  C-D
--------------------------------------------|---------|------------|------|----  E-F
```

I have a  GenomicInteraction object, among pairs, breakpointB overlaps with C, D overlaps with E. I want to group these 3 gi object together and assign the same ID to them, so I know these three are in a complex rearrangment event.

In a toy example, the first three pairs should be grouped as one

``` r
library(InteractionSet)
all.regions <- GRanges(rep("chrA",8), IRanges(c(1,4,5,9,10,15,20,22), c(3,6,7,11,13,19,25,27)))
index.1 <- c(1,3,5,7)
index.2 <- c(2,4,6,8) 

gi <- GInteractions(index.1, index.2, all.regions, mode ="strict")

gi
```

Thanks,
Ming

**Comment by LTLA** [comment]
Please post your question on the Bioconductor support site, as it gets more visibility there. Also, you may want to clarify what the dashes and pipes represent in your example. For starters, there's no way to tell whether the interval between the pipes represents a region or the gap between two regions.

**Comment by crazyhottommy** [comment]
thanks, I posted here https://support.bioconductor.org/p/85593/
