### ISSUE TITLE
first() and last()

### ISSUE THREAD

**Issue by lawremi** [LTLA/archive-InteractionSet#7]
Why not use `first()` and `last()` generics from GenomicAlignments (we can push them up to BiocGenerics or something) as a convenience for `anchors()`? It's true that "last" conflicts with "second". Need some consistency there.

**Comment by LTLA** [comment]
I'm open to this, if the generics are available somewhere.

**Comment by liz-is** [comment]
+1 to this. Consistency is good!

**Comment by lawremi** [comment]
I have asked Herve about pushing up the generics.

**Comment by LTLA** [comment]
The `first` and `second` methods from _S4Vectors_ are now supported in `GInteractions` objects.
