### ISSUE TITLE
connected components

### ISSUE THREAD

**Issue by lawremi** [LTLA/archive-InteractionSet#8]
It appears that there are use cases in the chromosome interaction sphere for graph-based reduction of overlapping ranges.  Here are some utilities that might help you get started. I have no idea where else to put them and don't want them lost in the ether ;)

```
setAs("Hits", "graph", function(from) {
          stopifnot(queryLength(from) == subjectLength(from))
          NEL <- split(subjectHits(from), queryHits(from))
          graph::graphNEL(names(NEL), NEL)
      })

splitByConnectedComps <- function(x) {
    g <- as(x, "graph")
    extractList(x, unname(RBGL::connectedComp(g)))
}
```

**Comment by LTLA** [comment]
Hmm... indeed, it seems easy enough to write a `setAs` to convert from a `GInteractions` object to a directed graph (this can then be coerced to a undirected graph if so desired). I can understand the appeal for network-based analyses and so on, but to be honest, I've never used such a data structure. I'm happy to throw in the converter, but any higher-level functions will be up to the discretion of individual package developers. Allowing for weights might be complicated though; I wonder if there's an `as.graph` generic we could use, with optional weights and `edgemode` specifications in the ellipsis.

**Comment by lawremi** [comment]
The use case as indicated by the support request (which has taken up a lot of my time this week) wants to reduce the interactions by overlap. So it would need to be forming a graph on the overlap Hits, not the GInteractions. I'm not really requesting any action here; just wanted to record this potential feature + code for prosterity ;)

**Comment by LTLA** [comment]
Oh, okay. Well, I guess I'll close this issue then.

**Comment by lawremi** [comment]
Maybe it's best to record on the support site. I'll move it there.
